apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: 242201292722.dkr.ecr.eu-north-1.amazonaws.com/montassar-app:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
